version: '3.4'

services:
  salesmanagementapi:
    image: "chk6622/sales_management_api"
    build:
      context: ./
      dockerfile: SalesManagementApi/Dockerfile

    privileged:
        true
    ports: 
      - "5000:80"
    networks: 
      - "asp-net"
    depends_on: 
      - mydb

  mydb:
    image: "mcr.microsoft.com/mssql/server:2017-CU8-ubuntu"
    environment: 
      SA_PASSWORD: "Xhy123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    networks: 
      - "asp-net"  

networks:
  asp-net:
    driver: bridge